### ISSUE TITLE
Segv Fault on Apple Silicon (Thry 2.43, 2.48)

### ISSUE THREAD

**Issue by MisutaaAsriel** [Thryrallo/ThryEditor#53]
## Issue
When locking shaders with the Poiyomi shader package, the included copy of Thry Editor triggers a `segv` fault and crashes the editor on Apple Silicon when calling `Thry.Helper:TryDetourFromTo`. Updating the included Thry Editor package to 2.48.0 does not fix this issue.

## Platform Information
- OS: macOS Sonoma 14.2
- Chipset: Apple M2
- RAM: 24GB

## Editor Information
- Unity 2022.3.6f1 (Silicon)
- VRC SDK 3.5.0-beta.1 (Live Release, VPM)
- Poiyomi (VPM)

## Versions Tested
- 2.43.X (Poiyomi bundled)
- 2.48.0 (Upgraded manually)

## Relevant log data:
```log
=================================================================
	Native Crash Reporting
=================================================================
Got a segv while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

…

=================================================================
	Managed Stacktrace:
=================================================================
	  at Thry.Helper:TryDetourFromTo <0x00148>
	  at Thry.ShaderOptimizer:DetourApplyMaterialPropertyDrawers <0x0002b>
	  at Thry.ShaderOptimizer:LockApplyShader <0x00183>
	  at Thry.ShaderOptimizer:LockApplyShader <0x0013b>
	  at Thry.ShaderOptimizer:SetLockedForAllMaterials <0x00fc7>
	  at Thry.ThryShaderOptimizerLockButtonDrawer:OnGUI <0x008e3>
	  at UnityEditor.MaterialPropertyDrawer:OnGUI <0x0009f>
	  at UnityEditor.MaterialPropertyHandler:OnGUI <0x00403>
	  at UnityEditor.MaterialEditor:ShaderPropertyInternal <0x00127>
	  at UnityEditor.MaterialEditor:ShaderProperty <0x000f3>
	  at UnityEditor.MaterialEditor:ShaderProperty <0x00093>
	  at UnityEditor.MaterialEditor:ShaderProperty <0x00027>
	  at Thry.ShaderProperty:DrawInternal <0x0086b>
	  at Thry.ShaderPart:PerformDraw <0x00057>
	  at Thry.ShaderPart:Draw <0x000eb>
	  at Thry.ShaderEditor:OnGUI <0x0027b>
	  at UnityEditor.MaterialEditor:PropertiesGUI <0x00237>
	  at UnityEditor.MaterialEditor:OnInspectorGUI <0x0009b>
	  at <>c__DisplayClass72_0:<CreateInspectorElementUsingIMGUI>b__0 <0x006b7>
	  at UnityEngine.UIElements.IMGUIContainer:DoOnGUI <0x006e3>
	  at UnityEngine.UIElements.IMGUIContainer:HandleIMGUIEvent <0x0035f>
	  at UnityEngine.UIElements.IMGUIContainer:HandleIMGUIEvent <0x00103>
	  at UnityEngine.UIElements.IMGUIContainer:HandleIMGUIEvent <0x0002f>
	  at UnityEngine.UIElements.IMGUIContainer:SendEventToIMGUIRaw <0x0008f>
	  at UnityEngine.UIElements.IMGUIContainer:SendEventToIMGUI <0x00467>
	  at UnityEngine.UIElements.IMGUIContainer:ProcessEvent <0x0003b>
	  at UnityEngine.UIElements.CallbackEventHandler:HandleEvent <0x00273>
	  at UnityEngine.UIElements.CallbackEventHandler:HandleEventAtCurrentTargetAndPhase <0x00027>
	  at UnityEngine.UIElements.CallbackEventHandler:HandleEventAtTargetPhase <0x0004b>
	  at UnityEngine.UIElements.MouseCaptureDispatchingStrategy:DispatchEvent <0x00537>
	  at UnityEngine.UIElements.EventDispatcher:ApplyDispatchingStrategies <0x000b7>
	  at UnityEngine.UIElements.EventDispatcher:ProcessEvent <0x0013b>
	  at UnityEngine.UIElements.EventDispatcher:ProcessEventQueue <0x000f7>
	  at UnityEngine.UIElements.EventDispatcher:OpenGate <0x0005f>
	  at UnityEngine.UIElements.EventDispatcherGate:Dispose <0x0001f>
	  at UnityEngine.UIElements.EventDispatcher:ProcessEvent <0x004b3>
	  at UnityEngine.UIElements.EventDispatcher:Dispatch <0x000f7>
	  at UnityEngine.UIElements.BaseVisualElementPanel:SendEvent <0x00067>
	  at UnityEngine.UIElements.UIElementsUtility:DoDispatch <0x003f7>
	  at UnityEngine.UIElements.UIElementsUtility:UnityEngine.UIElements.IUIElementsUtility.ProcessEvent <0x000c7>
	  at UnityEngine.UIElements.UIEventRegistration:ProcessEvent <0x00093>
	  at <>c:<.cctor>b__1_2 <0x0001f>
	  at UnityEngine.GUIUtility:ProcessEvent <0x00063>
	  at <Module>:runtime_invoke_void_int_intptr_intptr& <0x0007f>
=================================================================

Obtained 66 stack frames.
#0  0x000003320a9190 in  Thry.Helper:TryDetourFromTo (System.Reflection.MethodInfo,System.Reflection.MethodInfo) [{0x2bcff1a98} + 0x148] [./Packages/com.poiyomi.toon/_PoiyomiShaders/Scripts/ThryEditor/Editor/Helper.cs :: 291u] (0x3320a9048 0x3320a9464) [0x13b582a80 - Unity Child Domain]
#1  0x000003320a8fb4 in  Thry.ShaderOptimizer:DetourApplyMaterialPropertyDrawers () [{0x3501308a8} + 0x2c] [./Packages/com.poiyomi.toon/_PoiyomiShaders/Scripts/ThryEditor/Editor/ShaderOptimizer.cs :: 855u] (0x3320a8f88 0x3320a8fe4) [0x13b582a80 - Unity Child Domain]
#2  0x000003320a7dbc in  Thry.ShaderOptimizer:LockApplyShader (Thry.ShaderOptimizer/ApplyStruct) [{0x3501308f8} + 0x184] [./Packages/com.poiyomi.toon/_PoiyomiShaders/Scripts/ThryEditor/Editor/ShaderOptimizer.cs :: 894u] (0x3320a7c38 0x3320a87f4) [0x13b582a80 - Unity Child Domain]
#3  0x000003320a72dc in  Thry.ShaderOptimizer:LockApplyShader (UnityEngine.Material) [{0x350130830} + 0x13c] [./Packages/com.poiyomi.toon/_PoiyomiShaders/Scripts/ThryEditor/Editor/ShaderOptimizer.cs :: 841u] (0x3320a71a0 0x3320a72ec) [0x13b582a80 - Unity Child Domain]
#4  0x0000033207e388 in  Thry.ShaderOptimizer:SetLockedForAllMaterials (System.Collections.Generic.IEnumerable`1<UnityEngine.Material>,int,bool,bool,bool,UnityEditor.MaterialProperty) [{0x350130b78} + 0xfc8] [./Packages/com.poiyomi.toon/_PoiyomiShaders/Scripts/ThryEditor/Editor/ShaderOptimizer.cs :: 2287u] (0x33207d3c0 0x33207e5bc) [0x13b582a80 - Unity Child Domain]
#5  0x0000032f1e31e4 in  Thry.ThryShaderOptimizerLockButtonDrawer:OnGUI (UnityEngine.Rect,UnityEditor.MaterialProperty,string,UnityEditor.MaterialEditor) [{0x2aa329228} + 0x8e4] [./Packages/com.poiyomi.toon/_PoiyomiShaders/Scripts/ThryEditor/Editor/Drawers.cs :: 1889u] (0x32f1e2900 0x32f1e3518) [0x13b582a80 - Unity Child Domain]
#6  0x0000032f1e2738 in  UnityEditor.MaterialPropertyDrawer:OnGUI (UnityEngine.Rect,UnityEditor.MaterialProperty,UnityEngine.GUIContent,UnityEditor.MaterialEditor) [{0x2ba5e5fc8} + 0xa0] [/Users/bokken/build/output/unity/unity/Editor/Mono/Inspector/MaterialPropertyDrawer.cs :: 235u] (0x32f1e2698 0x32f1e2748) [0x13b582a80 - Unity Child Domain]
#7  0x0000032f1e25a4 in  UnityEditor.MaterialPropertyHandler:OnGUI (UnityEngine.Rect&,UnityEditor.MaterialProperty,UnityEngine.GUIContent,UnityEditor.MaterialEditor) [{0x350443438} + 0x404] [/Users/bokken/build/output/unity/unity/Editor/Mono/Inspector/MaterialPropertyDrawer.cs :: 50u] (0x32f1e21a0 0x32f1e2618) [0x13b582a80 - Unity Child Domain]
#8  0x0000032f1e1ff8 in  UnityEditor.MaterialEditor:ShaderPropertyInternal (UnityEngine.Rect,UnityEditor.MaterialProperty,UnityEngine.GUIContent) [{0x31fcf7398} + 0x128] [/Users/bokken/build/output/unity/unity/Editor/Mono/Inspector/MaterialEditor.cs :: 2009u] (0x32f1e1ed0 0x32f1e209c) [0x13b582a80 - Unity Child Domain]
#9  0x0000032f1e1924 in  UnityEditor.MaterialEditor:ShaderProperty (UnityEngine.Rect,UnityEditor.MaterialProperty,UnityEngine.GUIContent,int) [{0x31fcf7208} + 0xf4] [/Users/bokken/build/output/unity/unity/Editor/Mono/Inspector/MaterialEditor.cs :: 1822u] (0x32f1e1830 0x32f1e1990) [0x13b582a80 - Unity Child Domain]
#10 0x0000032f1e13e4 in  UnityEditor.MaterialEditor:ShaderProperty (UnityEditor.MaterialProperty,UnityEngine.GUIContent,int) [{0x31fcf7168} + 0x94] [/Users/bokken/build/output/unity/unity/Editor/Mono/Inspector/MaterialEditor.cs :: 1796u] (0x32f1e1350 0x32f1e13f8) [0x13b582a80 - Unity Child Domain]
#11 0x0000032f1e12f0 in  UnityEditor.MaterialEditor:ShaderProperty (UnityEditor.MaterialProperty,UnityEngine.GUIContent) [{0x31fcf7118} + 0x28] [/Users/bokken/build/output/unity/unity/Editor/Mono/Inspector/MaterialEditor.cs :: 1785u] (0x32f1e12c8 0x32f1e12fc) [0x13b582a80 - Unity Child Domain]
#12 0x0000032f1dc99c in  Thry.ShaderProperty:DrawInternal (UnityEngine.GUIContent,Thry.CRect,bool,bool) [{0x2ab762e38} + 0x86c] [./Packages/com.poiyomi.toon/_PoiyomiShaders/Scripts/ThryEditor/Editor/EditorStructs.cs :: 1405u] (0x32f1dc130 0x32f1dcb84) [0x13b582a80 - Unity Child Domain]
#13 0x0000032f1d9260 in  Thry.ShaderPart:PerformDraw (UnityEngine.GUIContent,Thry.CRect,bool,bool) [{0x32e995640} + 0x58] [./Packages/com.poiyomi.toon/_PoiyomiShaders/Scripts/ThryEditor/Editor/EditorStructs.cs :: 708u] (0x32f1d9208 0x32f1d97d0) [0x13b582a80 - Unity Child Domain]
#14 0x0000032f1d83b4 in  Thry.ShaderPart:Draw (Thry.CRect,UnityEngine.GUIContent,bool,bool) [{0x30d2ad2a0} + 0xec] [./Packages/com.poiyomi.toon/_PoiyomiShaders/Scripts/ThryEditor/Editor/EditorStructs.cs :: 345u] (0x32f1d82c8 0x32f1d83e8) [0x13b582a80 - Unity Child Domain]
#15 0x0000032f1bb3fc in  Thry.ShaderEditor:OnGUI (UnityEditor.MaterialEditor,UnityEditor.MaterialProperty[]) [{0x2aa327e10} + 0x27c] [./Packages/com.poiyomi.toon/_PoiyomiShaders/Scripts/ThryEditor/Editor/ThryEditor.cs :: 491u] (0x32f1bb180 0x32f1bb4cc) [0x13b582a80 - Unity Child Domain]
#16 0x0000032f1b9b28 in  UnityEditor.MaterialEditor:PropertiesGUI () [{0x31fcf7780} + 0x238] [/Users/bokken/build/output/unity/unity/Editor/Mono/Inspector/MaterialEditor.cs :: 2349u] (0x32f1b98f0 0x32f1b9c94) [0x13b582a80 - Unity Child Domain]
#17 0x0000032f1b90ec in  UnityEditor.MaterialEditor:OnInspectorGUI () [{0x31fd24228} + 0x9c] [/Users/bokken/build/output/unity/unity/Editor/Mono/Inspector/MaterialEditor.cs :: 904u] (0x32f1b9050 0x32f1b91e4) [0x13b582a80 - Unity Child Domain]
#18 0x0000032f1b7290 in  UnityEditor.UIElements.InspectorElement/<>c__DisplayClass72_0:<CreateInspectorElementUsingIMGUI>b__0 () [{0x32e909c88} + 0x6b8] [/Users/bokken/build/output/unity/unity/Editor/Mono/UIElements/Inspector/InspectorElement.cs :: 713u] (0x32f1b6bd8 0x32f1b753c) [0x13b582a80 - Unity Child Domain]
#19 0x0000032a78373c in  UnityEngine.UIElements.IMGUIContainer:DoOnGUI (UnityEngine.Event,UnityEngine.Matrix4x4,UnityEngine.Rect,bool,UnityEngine.Rect,System.Action,bool) [{0x2ba7f1270} + 0x6e4] [/Users/bokken/build/output/unity/unity/ModuleOverrides/com.unity.ui/Core/IMGUIContainer.cs :: 356u] (0x32a783058 0x32a784480) [0x13b582a80 - Unity Child Domain]
#20 0x00000329f3c2f0 in  UnityEngine.UIElements.IMGUIContainer:HandleIMGUIEvent (UnityEngine.Event,UnityEngine.Matrix4x4,UnityEngine.Rect,System.Action,bool) [{0x2ba7f1478} + 0x360] [/Users/bokken/build/output/unity/unity/ModuleOverrides/com.unity.ui/Core/IMGUIContainer.cs :: 678u] (0x329f3bf90 0x329f3c438) [0x13b582a80 - Unity Child Domain]
#21 0x00000329f3ba6c in  UnityEngine.UIElements.IMGUIContainer:HandleIMGUIEvent (UnityEngine.Event,System.Action,bool) [{0x2ba7f1450} + 0x104] [/Users/bokken/build/output/unity/unity/ModuleOverrides/com.unity.ui/Core/IMGUIContainer.cs :: 648u] (0x329f3b968 0x329f3ba8c) [0x13b582a80 - Unity Child Domain]
#22 0x00000329f3b900 in  UnityEngine.UIElements.IMGUIContainer:HandleIMGUIEvent (UnityEngine.Event,bool) [{0x2ba7f1428} + 0x30] [/Users/bokken/build/output/unity/unity/ModuleOverrides/com.unity.ui/Core/IMGUIContainer.cs :: 641u] (0x329f3b8d0 0x329f3b914) [0x13b582a80 - Unity Child Domain]
#23 0x00000329f3b338 in  UnityEngine.UIElements.IMGUIContainer:SendEventToIMGUIRaw (UnityEngine.UIElements.EventBase,bool,bool) [{0x2ba7f1338} + 0x90] [/Users/bokken/build/output/unity/unity/ModuleOverrides/com.unity.ui/Core/IMGUIContainer.cs :: 601u] (0x329f3b2a8 0x329f3b38c) [0x13b582a80 - Unity Child Domain]
#24 0x00000329f3b088 in  UnityEngine.UIElements.IMGUIContainer:SendEventToIMGUI (UnityEngine.UIElements.EventBase,bool,bool) [{0x2ba7f1310} + 0x468] [/Users/bokken/build/output/unity/unity/ModuleOverrides/com.unity.ui/Core/IMGUIContainer.cs :: 590u] (0x329f3ac20 0x329f3b0a8) [0x13b582a80 - Unity Child Domain]
#25 0x00000328e27424 in  UnityEngine.UIElements.IMGUIContainer:ProcessEvent (UnityEngine.UIElements.EventBase) [{0x2ba7f12c0} + 0x3c] [/Users/bokken/build/output/unity/unity/ModuleOverrides/com.unity.ui/Core/IMGUIContainer.cs :: 514u] (0x328e273e8 0x328e27504) [0x13b582a80 - Unity Child Domain]
#26 0x00000328e26f0c in  UnityEngine.UIElements.CallbackEventHandler:HandleEvent (UnityEngine.UIElements.EventBase) [{0x2aa257fc8} + 0x274] [/Users/bokken/build/output/unity/unity/ModuleOverrides/com.unity.ui/Core/Events/EventHandler.cs :: 270u] (0x328e26c98 0x328e27198) [0x13b582a80 - Unity Child Domain]
#27 0x00000328e26c70 in  UnityEngine.UIElements.CallbackEventHandler:HandleEventAtCurrentTargetAndPhase (UnityEngine.UIElements.EventBase) [{0x2ba985270} + 0x28] [/Users/bokken/build/output/unity/unity/ModuleOverrides/com.unity.ui/Core/Events/EventHandler.cs :: 193u] (0x328e26c48 0x328e26c94) [0x13b582a80 - Unity Child Domain]
#28 0x00000328e268ec in  UnityEngine.UIElements.CallbackEventHandler:HandleEventAtTargetPhase (UnityEngine.UIElements.EventBase) [{0x2ba985220} + 0x4c] [/Users/bokken/build/output/unity/unity/ModuleOverrides/com.unity.ui/Core/Events/EventHandler.cs :: 174u] (0x328e268a0 0x328e26914) [0x13b582a80 - Unity Child Domain]
#29 0x00000329f37a90 in  UnityEngine.UIElements.MouseCaptureDispatchingStrategy:DispatchEvent (UnityEngine.UIElements.EventBase,UnityEngine.UIElements.IPanel) [{0x350013278} + 0x538] [/Users/bokken/build/output/unity/unity/ModuleOverrides/com.unity.ui/Core/Events/MouseCaptureDispatchingStrategy.cs :: 92u] (0x329f37558 0x329f37cbc) [0x13b582a80 - Unity Child Domain]
#30 0x00000329e35e08 in  UnityEngine.UIElements.EventDispatcher:ApplyDispatchingStrategies (UnityEngine.UIElements.EventBase,UnityEngine.UIElements.IPanel,bool) [{0x2db74d100} + 0xb8] [/Users/bokken/build/output/unity/unity/ModuleOverrides/com.unity.ui/Core/EventDispatcher.cs :: 424u] (0x329e35d50 0x329e35f68) [0x13b582a80 - Unity Child Domain]
#31 0x00000329e35674 in  UnityEngine.UIElements.EventDispatcher:ProcessEvent (UnityEngine.UIElements.EventBase,UnityEngine.UIElements.IPanel) [{0x3500adb38} + 0x13c] [/Users/bokken/build/output/unity/unity/ModuleOverrides/com.unity.ui/Core/EventDispatcher.cs :: 368u] (0x329e35538 0x329e35a10) [0x13b582a80 - Unity Child Domain]
#32 0x00000328e0e6b8 in  UnityEngine.UIElements.EventDispatcher:ProcessEventQueue () [{0x3500adae8} + 0xf8] [/Users/bokken/build/output/unity/unity/ModuleOverrides/com.unity.ui/Core/EventDispatcher.cs :: 322u] (0x328e0e5c0 0x328e0e804) [0x13b582a80 - Unity Child Domain]
#33 0x00000328e0e550 in  UnityEngine.UIElements.EventDispatcher:OpenGate () [{0x2ba9847b8} + 0x60] [/Users/bokken/build/output/unity/unity/ModuleOverrides/com.unity.ui/Core/EventDispatcher.cs :: 287u] (0x328e0e4f0 0x328e0e560) [0x13b582a80 - Unity Child Domain]
#34 0x00000328e0e490 in  UnityEngine.UIElements.EventDispatcherGate:Dispose () [{0x2ba9846d0} + 0x20] [/Users/bokken/build/output/unity/unity/ModuleOverrides/com.unity.ui/Core/EventDispatcher.cs :: 78u] (0x328e0e470 0x328e0e4a0) [0x13b582a80 - Unity Child Domain]
#35 0x00000329e359ec in  UnityEngine.UIElements.EventDispatcher:ProcessEvent (UnityEngine.UIElements.EventBase,UnityEngine.UIElements.IPanel) [{0x3500adb38} + 0x4b4] [/Users/bokken/build/output/unity/unity/ModuleOverrides/com.unity.ui/Core/EventDispatcher.cs :: 413u] (0x329e35538 0x329e35a10) [0x13b582a80 - Unity Child Domain]
#36 0x00000329e325a8 in  UnityEngine.UIElements.EventDispatcher:Dispatch (UnityEngine.UIElements.EventBase,UnityEngine.UIElements.IPanel,UnityEngine.UIElements.DispatchMode) [{0x2db74c448} + 0xf8] [/Users/bokken/build/output/unity/unity/ModuleOverrides/com.unity.ui/Core/EventDispatcher.cs :: 230u] (0x329e324b0 0x329e32744) [0x13b582a80 - Unity Child Domain]
#37 0x00000329e32440 in  UnityEngine.UIElements.BaseVisualElementPanel:SendEvent (UnityEngine.UIElements.EventBase,UnityEngine.UIElements.DispatchMode) [{0x2db74c3f0} + 0x68] [/Users/bokken/build/output/unity/unity/ModuleOverrides/com.unity.ui/Core/Panel.cs :: 458u] (0x329e323d8 0x329e32450) [0x13b582a80 - Unity Child Domain]
#38 0x00000329f1a0d0 in  UnityEngine.UIElements.UIElementsUtility:DoDispatch (UnityEngine.UIElements.BaseVisualElementPanel) [{0x350388040} + 0x3f8] [/Users/bokken/build/output/unity/unity/ModuleOverrides/com.unity.ui/Core/UIElementsUtility.cs :: 477u] (0x329f19cd8 0x329f1a20c) [0x13b582a80 - Unity Child Domain]
#39 0x00000329f19a90 in  UnityEngine.UIElements.UIElementsUtility:UnityEngine.UIElements.IUIElementsUtility.ProcessEvent (int,intptr,bool&) [{0x2ba9e4298} + 0xc8] [/Users/bokken/build/output/unity/unity/ModuleOverrides/com.unity.ui/Core/UIElementsUtility.cs :: 205u] (0x329f199c8 0x329f19ac0) [0x13b582a80 - Unity Child Domain]
#40 0x00000329f19854 in  UnityEngine.UIElements.UIEventRegistration:ProcessEvent (int,intptr) [{0x350387f80} + 0x94] [/Users/bokken/build/output/unity/unity/ModuleOverrides/com.unity.ui/Core/UIElementsUtility.cs :: 74u] (0x329f197c0 0x329f198e8) [0x13b582a80 - Unity Child Domain]
#41 0x00000329f19760 in  UnityEngine.UIElements.UIEventRegistration/<>c:<.cctor>b__1_2 (int,intptr) [{0x2ba9e4ef8} + 0x20] [/Users/bokken/build/output/unity/unity/ModuleOverrides/com.unity.ui/Core/UIElementsUtility.cs :: 28u] (0x329f19740 0x329f19770) [0x13b582a80 - Unity Child Domain]
#42 0x00000329f195a4 in  UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&) [{0x2d4b4b1a0} + 0x64] [/Users/bokken/build/output/unity/unity/Modules/IMGUI/GUIUtility.cs :: 190u] (0x329f19540 0x329f195bc) [0x13b582a80 - Unity Child Domain]
#43 0x00000329f19640 in  (wrapper runtime-invoke) <Module>:runtime_invoke_void_int_intptr_intptr& (object,intptr,intptr,intptr) [{0x35013b438} + 0x80]  (0x329f195c0 0x329f196ec) [0x13b582a80 - Unity Child Domain]
#44 0x00000168f8133c in mono_jit_runtime_invoke
#45 0x00000169107594 in do_runtime_invoke
#46 0x000001691074b4 in mono_runtime_invoke
#47 0x00000102f97ea8 in scripting_method_invoke(ScriptingMethodPtr, ScriptingObjectPtr, ScriptingArguments&, ScriptingExceptionPtr*, bool)
#48 0x00000102f748d4 in ScriptingInvocation::Invoke(ScriptingExceptionPtr*, bool)
#49 0x000001030ba000 in Scripting::UnityEngine::GUIUtilityProxy::ProcessEvent(int, void*, bool*, ScriptingExceptionPtr*)
#50 0x000001039b6078 in GUIView::ProcessRetainedMode(InputEvent&, GUIState&, int)
#51 0x00000104dab770 in GUIView::OnInputEvent(InputEvent&)
#52 0x000001039b54ac in GUIView::ProcessInputEvent(InputEvent&)
#53 0x00000104db9410 in -[GUIRenderView handleEvent:]
#54 0x00000104db9bc8 in -[GUIRenderView mouseUp:]
#55 0x0000018ade632c in _routeMouseUpEvent
#56 0x976c80018a3f5048 in -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:]
#57 0x686180018a3f4cf4 in -[NSWindow(NSEventRouting) sendEvent:]
#58 0xc25e00018aa9f328 in -[NSApplication(NSEventRouting) sendEvent:]
#59 0xda05000104db09dc in -[EditorApplicationPrincipalClass sendEvent:]
#60 0x0000018a6f1014 in -[NSApplication _handleEvent:]
#61 0x627400018a2bcab4 in -[NSApplication run]
#62 0x795500018a293d58 in NSApplicationMain
#63 0xfc7a000104db1250 in EditorMain(int, char const**)
#64 0x00000104db159c in main
#65 0x000001866950e0 in start
Launching bug reporter
Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created.
[40m[32minfo[39m[22m[49m: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
[40m[32minfo[39m[22m[49m: Unity.ILPP.Runner.PostProcessingAssemblyLoadContext[0]
      ALC ILPP context 1 is unloading
```

**Comment by Thryrallo** [comment]
Added a preprocessor statement that should fix this
